### ISSUE TITLE
compatibility to VueRouter is challenging

### ISSUE THREAD

**Issue by thomasreinecke** [MisRob/vue-tree-navigation#29]
hi, thanks for this great work - I like it a lot even though it has some challenges because its lacking a closer integration with VueRouter. Background : I construct my VueRouter and vue-tree-navigation items dynamically from a simple JSON object. Doing so reveals the following issues

- the vue-tree-navigation module uses a property `route` as routing context, VueRouter uses `path` - please align this to also use `path`
- wouldnt it be great if vue-tree-navigation could be initialized in a way to pickup its items from VueRouter ? This would eliminate the steps to create config thats in sync for both

Thanks

**Comment by MisRob** [comment]
Hey again,

as regards to 1., I checked codes in detail and spent more time on it and realized that I forgot about new behavior of v3 :) Currently, it works with router or without the router and both of these modes use `route` field. So it will be really better to name it `path`. It will be clear for people who want to use the library with router because we are all used to this name. And for people who don't want to use it together with router, path will be actually more intuitive name, too.

Thanks for noticing!

**Comment by MisRob** [comment]
Implemented. Will be released as v4.0.0.
